export default {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: false,
  trailingComma: "es5",
  bracketSpacing: true,
  bracketSameLine: false,
  objectWrap: "collapse",
  arrowParens: "always",
  proseWrap: "always",
  endOfLine: "lf",
  embeddedLanguageFormatting: "off",

  plugins: ["@ianvs/prettier-plugin-sort-imports"],
  importOrder: [
    "",
    "<TYPES>",
    "",
    "<BUILTIN_MODULES>",
    "",
    "<THIRD_PARTY_MODULES>",
    "",
    "",
    "^\\.\\.($|/)",
    "",
    "^\\./[^/]*/[^/]*/",
    "^\\./[^/]*/",
    "^\\.($|/)",
  ],
  importOrderCaseSensitive: true,
  importOrderTypeScriptVersion: "6.0.0",
}
